config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :teachers do
    get '/dashboard', to: 'teachers#dashboard'
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index show edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :teacher

  validates :start_time, :end_time, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  CATEGORIES = ["Front-End Specialist", "Back-End Specialist", "Full Stack Specialist"]
  validates :description, presence: true, length: { minimum: 10 }
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :teacher, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name username])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings # .where('start_time >= ?', Time.current)
    if @bookings.empty?
      redirect_to teachers_path, notice: 'You do not have any bookings yet.'
    else
      @bookings
    end

    # if params[:start_time]
    #   @bookings = @bookings.where('start_time >= ?', params[:start_time])
    # end
  end

  def show
    @booking = current_user.bookings.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to teacher_dashboard_path(current_user)
  end

  def new
    @teacher = Teacher.find(params[:teacher_id])
    @booking = @teacher.bookings.new
  end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    @booking = current_user.bookings.new(booking_params)
    @booking.teacher = @teacher
    if @booking.save
      redirect_to teacher_dashboard_path(current_user),
                  alert: 'You created a new Booking! Your Teacher will ' \
                         'contact you once they have accepted your booking'
    else
      render :new
    end
  end

  def edit
    @booking = current_user.bookings.find(params[:id])
  end

  def update
    @booking = current_user.bookings.find(params[:id])
    @booking.update(booking_params)
    if @booking.save
      redirect_to teacher_dashboard_path(current_user),
                  notice: 'The booking is updated.'
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[show edit update destroy]

  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.user = current_user
    if @teacher.save
      redirect_to teacher_path(@teacher), alert: 'Your teacher profile was successfully created.'
    else
      render :new
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to teacher_path(@teacher), alert: 'Your teacher profile was successfully updated.'
    else
      render :edit
    end
  end

  def dashboard
    @user = current_user
    @bookings = current_user.bookings
    # @teacher = current_user.bookings.teacher.id
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def destroy
    @teacher.destroy
    redirect_to root_path, alert: 'You have successfully deleted your teacher profile.'
  end

  private

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:description, :category, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <h1 class="pt-5">Edit</h1>

  <%= simple_form_for @booking do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :start_time, as: :date, html5: true %>
      <%= f.input :end_time, as: :date, html5: true %>
    </div>

    <div class="form-actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<h1>Hello Here are all my bookings</h1>

<%= @bookings.each do |booking| %>
  <div>
    <%= booking %>
    <%= link_to '✎ Edit', edit_booking_path(booking) %>
    <%= link_to 'Delete', booking_path(booking), method: :delete, data: { confirm: 'Are you sure? there is no refunds!!!' } %>
  <div>
<% end %>

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="pt-5">New booking</h1>

  <%= simple_form_for([@teacher, @booking]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :start_time, as: :date, html5: true, label: 'Start Date' %>
      <%= f.input :end_time, as: :date, html5: true, label: 'End Date'  %>
    </div>

    <div class="form-actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CODEX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

app/views/pages/home.html.erb
<div class="homepage-banner">
  <div class="background-image">
    <%= image_tag asset_path('homepage-potential4.jpg') %>
  </div>
</div>

<div class="body">
  <div class="search-bar">

    <div class="button1 px-5">
    <%= link_to 'SHOW ALL TA\'s', teachers_path%>
    </div>
    <div class="button2 px-5">
    <%= link_to 'REGISTER AS TA', new_teacher_path %>
    </div>
  </div>
  <div class="subheading">
    <h4>What do you want to learn?</h4>
  </div>

  <div class="cards">
    <div class="card1">
      <a href="">Front-End Development</a>
    </div>
    <div class="card2">
      <a href="">Back-End Development</a>
    </div>
    <div class="card3">
      <a href="">Full Stack Development</a>
    </div>
  </div>

  <div class="subheading">
    <h4>Some of our TA's...</h4>
  </div>

  <div class="list-of-TAs">
    <div class="TA-one">
      <%= image_tag asset_path('TAimage1.png') %>
      <h5>Megan Thresh</h5>
      <p>Full Stack Developer
      JavaScript, Ruby, CSS
      London</p>
    </div>
    <div class="TA-two">
      <%= image_tag asset_path('TA-image2.png') %>
      <h5>Patricia Falandysz</h5>
      <p>Front-End Developer
      Paris</p>
    </div>
    <div class="TA-three">
      <%= image_tag asset_path('TAimage3.png') %>
      <h5>Saile Ribeiro</h5>
      <p>Full Stack Developer
      Python, React, JavaScript
      Sao Paulo</p>
    </div>
    <div class="TA-four">
      <%= image_tag asset_path('TAimage4.png') %>
      <h5>Diego Garza</h5>
      <p>Full Stack Developer
      Ruby, Rails, Front-end
      London</p>
    </div>
  </div>

<br>
<br>

  <div>
    <% if user_signed_in? %>
      <%= link_to 'See all the TAs we have', teachers_path, class:"path-buttons py-3 px-5" %>
      <%= link_to 'Register yourself as a TA', new_teacher_path, class: "path-buttons py-3 px-5" %>
    <% else %>
      <%= link_to 'See all the TAs we have', teachers_path, class:"path-buttons py-3 px-5" %>
    <% end %>
  </div>
<br>
<br>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/miabellavia/CODEX"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonlondon/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagonlondon/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/LeWagonLondon?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/le-wagon/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    We All <i class="fas fa-heart"></i> CODEX 2021©
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <div class="logo">
    <%= image_tag asset_path('logo_CODEX_black.png') %>
  </div>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item1 active">
          <%= link_to current_user.first_name, teacher_dashboard_path(current_user), class: "nav-link text-white" %>
        </li>
        <li class="nav-item2 text-white">
          <%= link_to "Messages", "#", class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{current_user.username}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", teacher_dashboard_path(current_user), class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>

        <li class="nav-item1">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item2">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/teachers/_form.html.erb
<div class='form'>
<div class="container">
<h3 class="pt-5 text-white">Make yourself a TA</h3>
<% categories = ["What do you specialise in?", "Front-End Specialist", "Back-End Specialist", "Full Stack Specialist"] %>
<br>
  <%= simple_form_for(@teacher) do |f| %>
    <%= f.input :description, class: 'input-new', placeholder: 'Please enter a description about yourself', label: false  %>
    <%= f.input :price, class: 'input-new', placeholder: 'What price do you charge per day? (Input in GBP)', label: false %>
    <%= f.select :category, categories, style: "text-align: center;" %>
<div>
  <br>
    <%= f.button :submit, class: 'path-buttons py-3 px-5'%>
  </div>
  </div>
  <% end %>
  </div>

app/views/teachers/_teacher.html.erb
<%= link_to teacher, class: 'teacher_card-category', style: "height: 220px; background-image: url('https://kitt.lewagon.com/placeholder/users/#{teacher.user.username}')" do %>
  <div class="teacher_card-text">
    <%= teacher.user.first_name %> <%= teacher.user.last_name %>
    <p><%= teacher.category %> <br>
    <%= "£#{teacher.price.to_i} per day" %></p>
  </div>
<% end %>

app/views/teachers/dashboard.html.erb
<div class="list-booking pt-5">
  <div class="container">
  <h1 class="mt-4"> Your bookings </h1>
    <ul class="list">

      <% @bookings.each do |booking| %>

        <li class="list-item"><%= image_tag "https://kitt.lewagon.com/placeholder/users/#{booking.teacher.user.username}", class: "avatar-large" %>
          <div class="list-content">
            <%= link_to teacher_path(booking.teacher) do %>
              <div>
                <%= booking.teacher.user.first_name %> <%= booking.teacher.user.last_name %>
              </div>
            <% end %>
            <p>Start Date: <%= booking.start_time.strftime('%Y-%m-%d') %> End Date: <%= booking.end_time.strftime('%Y-%m-%d') %></p>
          </div>

          <div class="list-actions a">
            <%= link_to " Edit" , edit_booking_path(booking), class:"card-btn fas fa-pencil-alt" %>
            <%= link_to " Delete" , booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class:"card-btn far fa-trash-alt" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<br>
<br>

</div>
<%= link_to "Home" , teachers_path, class:"path-buttons py-3 px-5" %>
</div>

<br>
<br>

app/views/teachers/edit.html.erb
<div class="d-flex justify-content-center">
  <%= render 'form', teacher: @teacher %>
  <%= link_to 'Back', teachers_path %>
</div>

app/views/teachers/index.html.erb
<div class="container">
  <div class="header">
    <h1 class="pt-5">Our Teachers</h1>
  </div>

  <div class="teacher_card_container">
    <div class="teacher_cards">
      <%= render @teachers %>
    </div>
  </div>
</div>

<br>
<br>
<%= link_to 'Home', root_path, class: "path-buttons py-3 px-5" %>
<br>
<br>

app/views/teachers/new.html.erb
<div class="container">
  <%= render 'form', teacher: @teacher, class: "col-sm-2 col-form-label col-form-label-lg" %>
  <br>
  <br>
  <br>
  <%= link_to 'Back', teachers_path, class: 'path-buttons py-3 px-5' %>
  <br>
  <br>
</div>

app/views/teachers/show.html.erb
<div class="custom-container" id="show-page" class="container">
  <div class="box">
    <div id="overlay">
     <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{@teacher.user.username}", class: "image" %>
        <div class="trick">
      </div>
      </div>
      <ul class="text" id="name"><%= @teacher.user.first_name.capitalize %> <%= @teacher.user.last_name.capitalize %></ul>
      <br>
      <div class="text" id="category"><%= @teacher.category %></div>
      <br>
      <div class="text" id="price"><%= "£#{@teacher.price.to_i} per day" %></div>
      <br>




 <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
   <div class="panel panel-default">
     <div class="panel-heading " role="tab" id="headingOne">
       <h4 class="panel-title ">
         <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="" aria-controls="collapseOne">
           <div class="title  btn btn-danger btn-outline btn-lg" id="buttond">Click to see <%= @teacher.user.first_name.capitalize %>'s description</div>
         </a>
       </h4>
     </div>
     <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
       <div class="panel-body">
         <%= @teacher.description.capitalize %>
       </div>
     </div>

   </div>
   <div class="panel panel-default">
     <div class="panel-heading" role="tab" id="headingThree">
       <h4 class="panel-title">
         <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                   <%= link_to 'Book this TA now!', new_teacher_booking_path(@teacher), class: "title btn btn-danger btn-outline btn-lg" %>         </a>
       </h4>
     </div>
     <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
       <div class="panel-body">
          <%= link_to 'Book', new_teacher_booking_path(@teacher), class: "btn btn-primary w-100" %>

       </div>
     </div>
   </div>
 </div>
</div>
</div>
<%= link_to 'Choose a different TA', teachers_path, class: "path-buttons" %>
<%= link_to 'Back to the home page', root_path, class: "path-buttons" %>